export const VALIDATION = {
  AUTH: {
    USERNAME_MIN_LENGTH: 6,
    USERNAME_MAX_LENGTH: 20,
    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MAX_LENGTH: 20,
  },
  INSTALLMENT: {
    TITLE_MIN_LENGTH: 3,
    TITLE_MAX_LENGTH: 50,
    AMOUNT_MIN: 0,
    MONTH_COUNT_MIN: 1,
    MONTHLY_PAYMENT_AMOUNT_MIN: 0,
  },
};
